- repo: https://github.com/awebdeveloper/pre-commit-tslint/
  rev: master
  hooks:
    - id: tslint
      args: ['--project','tsconfig.json','-c', 'tslint.json']
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-json
    - id: check-merge-conflict
    - id: check-case-conflict
